// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
	"time"
)

type Declaration struct {
	Identifier  string
	Type        string
	Payload     string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	TouchedCt   int32
	ServerToken string
}

type EnrollmentSet struct {
	EnrollmentID string
	SetName      string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type SetDeclaration struct {
	SetName               string
	DeclarationIdentifier string
	CreatedAt             time.Time
	UpdatedAt             time.Time
}

type StatusDeclaration struct {
	EnrollmentID          string
	DeclarationIdentifier string
	Active                bool
	Valid                 string
	ServerToken           string
	ItemType              string
	Reasons               sql.NullString
	StatusID              sql.NullString
	CreatedAt             time.Time
	UpdatedAt             time.Time
}

type StatusError struct {
	ID           int64
	EnrollmentID string
	Path         string
	Error        string
	StatusID     sql.NullString
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type StatusReport struct {
	ID           int64
	EnrollmentID string
	StatusReport string
	StatusID     sql.NullString
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type StatusValue struct {
	EnrollmentID  string
	Path          string
	ContainerType string
	ValueType     string
	Value         string
	StatusID      sql.NullString
	CreatedAt     time.Time
	UpdatedAt     time.Time
}
