// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/lib/pq"
)

const deleteDeclaration = `-- name: DeleteDeclaration :execresult
DELETE FROM declarations WHERE identifier = $1
`

func (q *Queries) DeleteDeclaration(ctx context.Context, identifier string) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteDeclaration, identifier)
}

const deleteStatusErrors = `-- name: DeleteStatusErrors :exec
DELETE FROM
    status_errors
WHERE
    status_errors.enrollment_id = $1
    AND status_errors.id <= (
        SELECT se.id FROM status_errors se
        WHERE se.enrollment_id = $1
        ORDER BY se.id DESC
        LIMIT 1 OFFSET $2
    )
`

type DeleteStatusErrorsParams struct {
	EnrollmentID string
	Keep         int32
}

// Keeps only the newest (offset) errors for the enrollment.
func (q *Queries) DeleteStatusErrors(ctx context.Context, arg DeleteStatusErrorsParams) error {
	_, err := q.db.ExecContext(ctx, deleteStatusErrors, arg.EnrollmentID, arg.Keep)
	return err
}

const deleteStatusReports = `-- name: DeleteStatusReports :exec
DELETE FROM
    status_reports
WHERE
    status_reports.enrollment_id = $1
    AND status_reports.id <= (
        SELECT sr.id FROM status_reports sr
        WHERE sr.enrollment_id = $1
        ORDER BY sr.id DESC
        LIMIT 1 OFFSET $2
    )
`

type DeleteStatusReportsParams struct {
	EnrollmentID string
	Keep         int32
}

// Keeps only the newest (offset) status reports for the enrollment.
func (q *Queries) DeleteStatusReports(ctx context.Context, arg DeleteStatusReportsParams) error {
	_, err := q.db.ExecContext(ctx, deleteStatusReports, arg.EnrollmentID, arg.Keep)
	return err
}

const getDDMDeclaration = `-- name: GetDDMDeclaration :one
SELECT
    jsonb_build_object(
        'Identifier',  d.identifier,
        'Type',        d.type,
        'Payload',     d.payload,
        'ServerToken', d.server_token
    ) AS declaration
FROM
    declarations d
    INNER JOIN set_declarations sd
        ON d.identifier = sd.declaration_identifier
    INNER JOIN enrollment_sets es
        ON sd.set_name = es.set_name
WHERE
    d.identifier = $1 AND
    es.enrollment_id = $2 AND
    d.type LIKE $3
LIMIT 1
`

type GetDDMDeclarationParams struct {
	Identifier   string
	EnrollmentID string
	Type         string
}

func (q *Queries) GetDDMDeclaration(ctx context.Context, arg GetDDMDeclarationParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getDDMDeclaration, arg.Identifier, arg.EnrollmentID, arg.Type)
	var declaration string
	err := row.Scan(&declaration)
	return declaration, err
}

const getDeclaration = `-- name: GetDeclaration :one
SELECT
    d.identifier,
    d.type,
    d.payload,
    d.server_token,
    jsonb_build_object(
        'Identifier',  d.identifier,
        'Type',        d.type,
        'Payload',     d.payload,
        'ServerToken', d.server_token
    ) AS declaration
FROM
    declarations d
WHERE
    d.identifier = $1
`

type GetDeclarationRow struct {
	Identifier  string
	Type        string
	Payload     string
	ServerToken string
	Declaration string
}

func (q *Queries) GetDeclaration(ctx context.Context, identifier string) (GetDeclarationRow, error) {
	row := q.db.QueryRowContext(ctx, getDeclaration, identifier)
	var i GetDeclarationRow
	err := row.Scan(
		&i.Identifier,
		&i.Type,
		&i.Payload,
		&i.ServerToken,
		&i.Declaration,
	)
	return i, err
}

const getDeclarationIdentifiers = `-- name: GetDeclarationIdentifiers :many
SELECT identifier FROM declarations
`

func (q *Queries) GetDeclarationIdentifiers(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getDeclarationIdentifiers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var identifier string
		if err := rows.Scan(&identifier); err != nil {
			return nil, err
		}
		items = append(items, identifier)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDeclarationModTime = `-- name: GetDeclarationModTime :one
SELECT updated_at FROM declarations WHERE identifier = $1
`

func (q *Queries) GetDeclarationModTime(ctx context.Context, identifier string) (time.Time, error) {
	row := q.db.QueryRowContext(ctx, getDeclarationModTime, identifier)
	var updated_at time.Time
	err := row.Scan(&updated_at)
	return updated_at, err
}

const getDeclarationSets = `-- name: GetDeclarationSets :many
SELECT set_name FROM set_declarations WHERE declaration_identifier = $1
`

func (q *Queries) GetDeclarationSets(ctx context.Context, declarationIdentifier string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getDeclarationSets, declarationIdentifier)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var set_name string
		if err := rows.Scan(&set_name); err != nil {
			return nil, err
		}
		items = append(items, set_name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDeclarationStatus = `-- name: GetDeclarationStatus :many
SELECT
    sd.enrollment_id,
    sd.declaration_identifier,
    sd.active,
    sd.valid,
    sd.reasons,
    sd.server_token,
    sd.updated_at,
    sd.status_id,
    sd.server_token = COALESCE(d.server_token, '') AS current
FROM
    status_declarations sd
    LEFT JOIN declarations d
        ON sd.declaration_identifier = d.identifier
WHERE
    sd.enrollment_id = ANY($1::text[])
ORDER BY
    sd.enrollment_id
`

type GetDeclarationStatusRow struct {
	EnrollmentID          string
	DeclarationIdentifier string
	Active                bool
	Valid                 string
	Reasons               sql.NullString
	ServerToken           string
	UpdatedAt             time.Time
	StatusID              sql.NullString
	Current               bool
}

func (q *Queries) GetDeclarationStatus(ctx context.Context, ids []string) ([]GetDeclarationStatusRow, error) {
	rows, err := q.db.QueryContext(ctx, getDeclarationStatus, pq.Array(ids))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDeclarationStatusRow
	for rows.Next() {
		var i GetDeclarationStatusRow
		if err := rows.Scan(
			&i.EnrollmentID,
			&i.DeclarationIdentifier,
			&i.Active,
			&i.Valid,
			&i.Reasons,
			&i.ServerToken,
			&i.UpdatedAt,
			&i.StatusID,
			&i.Current,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEnrollmentIDs = `-- name: GetEnrollmentIDs :many
SELECT DISTINCT
    es.enrollment_id
FROM
    enrollment_sets es
    LEFT JOIN set_declarations sd
        ON sd.set_name = es.set_name
    LEFT JOIN declarations d
        ON d.identifier = sd.declaration_identifier
WHERE
    d.identifier = ANY($1::text[]) OR
    es.set_name = ANY($2::text[]) OR
    es.enrollment_id = ANY($3::text[])
`

type GetEnrollmentIDsParams struct {
	Declarations []string
	Sets         []string
	Ids          []string
}

// An empty array matches nothing, so unused filters drop out of the OR.
func (q *Queries) GetEnrollmentIDs(ctx context.Context, arg GetEnrollmentIDsParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getEnrollmentIDs, pq.Array(arg.Declarations), pq.Array(arg.Sets), pq.Array(arg.Ids))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var enrollment_id string
		if err := rows.Scan(&enrollment_id); err != nil {
			return nil, err
		}
		items = append(items, enrollment_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEnrollmentSets = `-- name: GetEnrollmentSets :many
SELECT set_name FROM enrollment_sets WHERE enrollment_id = $1
`

func (q *Queries) GetEnrollmentSets(ctx context.Context, enrollmentID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getEnrollmentSets, enrollmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var set_name string
		if err := rows.Scan(&set_name); err != nil {
			return nil, err
		}
		items = append(items, set_name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getManifestItems = `-- name: GetManifestItems :many
SELECT DISTINCT
    d.identifier,
    d.type,
    d.server_token
FROM
    declarations d
    INNER JOIN set_declarations sd
        ON d.identifier = sd.declaration_identifier
    INNER JOIN enrollment_sets es
        ON sd.set_name = es.set_name
WHERE
    es.enrollment_id = $1
`

type GetManifestItemsRow struct {
	Identifier  string
	Type        string
	ServerToken string
}

func (q *Queries) GetManifestItems(ctx context.Context, enrollmentID string) ([]GetManifestItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, getManifestItems, enrollmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetManifestItemsRow
	for rows.Next() {
		var i GetManifestItemsRow
		if err := rows.Scan(&i.Identifier, &i.Type, &i.ServerToken); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSetDeclarations = `-- name: GetSetDeclarations :many
SELECT declaration_identifier FROM set_declarations WHERE set_name = $1
`

func (q *Queries) GetSetDeclarations(ctx context.Context, setName string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getSetDeclarations, setName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var declaration_identifier string
		if err := rows.Scan(&declaration_identifier); err != nil {
			return nil, err
		}
		items = append(items, declaration_identifier)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSets = `-- name: GetSets :many
SELECT DISTINCT set_name FROM set_declarations
`

func (q *Queries) GetSets(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getSets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var set_name string
		if err := rows.Scan(&set_name); err != nil {
			return nil, err
		}
		items = append(items, set_name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStatusValues = `-- name: GetStatusValues :many
SELECT
    enrollment_id,
    path,
    value,
    status_id,
    updated_at
FROM
    status_values
WHERE
    enrollment_id = ANY($1::text[]) AND
    ($2::text IS NULL OR path LIKE $2::text)
ORDER BY
    enrollment_id, created_at
`

type GetStatusValuesParams struct {
	Ids        []string
	PathPrefix sql.NullString
}

type GetStatusValuesRow struct {
	EnrollmentID string
	Path         string
	Value        string
	StatusID     sql.NullString
	UpdatedAt    time.Time
}

func (q *Queries) GetStatusValues(ctx context.Context, arg GetStatusValuesParams) ([]GetStatusValuesRow, error) {
	rows, err := q.db.QueryContext(ctx, getStatusValues, pq.Array(arg.Ids), arg.PathPrefix)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStatusValuesRow
	for rows.Next() {
		var i GetStatusValuesRow
		if err := rows.Scan(
			&i.EnrollmentID,
			&i.Path,
			&i.Value,
			&i.StatusID,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertStatusError = `-- name: InsertStatusError :exec
INSERT INTO status_errors (
    enrollment_id,
    path,
    error,
    status_id
) VALUES ($1, $2, $3, $4)
`

type InsertStatusErrorParams struct {
	EnrollmentID string
	Path         string
	Error        string
	StatusID     sql.NullString
}

func (q *Queries) InsertStatusError(ctx context.Context, arg InsertStatusErrorParams) error {
	_, err := q.db.ExecContext(ctx, insertStatusError,
		arg.EnrollmentID,
		arg.Path,
		arg.Error,
		arg.StatusID,
	)
	return err
}

const insertStatusReport = `-- name: InsertStatusReport :exec
INSERT INTO status_reports (
    enrollment_id,
    status_id,
    status_report
) VALUES ($1, $2, $3)
`

type InsertStatusReportParams struct {
	EnrollmentID string
	StatusID     sql.NullString
	StatusReport string
}

func (q *Queries) InsertStatusReport(ctx context.Context, arg InsertStatusReportParams) error {
	_, err := q.db.ExecContext(ctx, insertStatusReport, arg.EnrollmentID, arg.StatusID, arg.StatusReport)
	return err
}

const putDeclarationStatus = `-- name: PutDeclarationStatus :exec
INSERT INTO status_declarations (
    enrollment_id,
    item_type,
    declaration_identifier,
    active,
    valid,
    server_token,
    reasons,
    status_id
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type PutDeclarationStatusParams struct {
	EnrollmentID          string
	ItemType              string
	DeclarationIdentifier string
	Active                bool
	Valid                 string
	ServerToken           string
	Reasons               sql.NullString
	StatusID              sql.NullString
}

func (q *Queries) PutDeclarationStatus(ctx context.Context, arg PutDeclarationStatusParams) error {
	_, err := q.db.ExecContext(ctx, putDeclarationStatus,
		arg.EnrollmentID,
		arg.ItemType,
		arg.DeclarationIdentifier,
		arg.Active,
		arg.Valid,
		arg.ServerToken,
		arg.Reasons,
		arg.StatusID,
	)
	return err
}

const putStatusValues = `-- name: PutStatusValues :exec
INSERT INTO status_values
    (enrollment_id, path, container_type, value_type, value, status_id)
SELECT DISTINCT
    $1::text,
    v.path,
    v.container_type,
    v.value_type,
    v.value,
    $2::text
FROM
    -- the unnests zip the equal-length arrays by position.
    (
        SELECT
            unnest($3::text[])           AS path,
            unnest($4::text[]) AS container_type,
            unnest($5::text[])     AS value_type,
            unnest($6::text[])            AS value
    ) v
ON CONFLICT (enrollment_id, path, container_type, value_type, value) DO UPDATE
SET
    updated_at = CURRENT_TIMESTAMP,
    status_id  = excluded.status_id
`

type PutStatusValuesParams struct {
	EnrollmentID   string
	StatusID       sql.NullString
	Paths          []string
	ContainerTypes []string
	ValueTypes     []string
	Vals           []string
}

// DISTINCT collapses values a report repeats: PostgreSQL refuses to update
// the same row twice in one INSERT ... ON CONFLICT DO UPDATE.
func (q *Queries) PutStatusValues(ctx context.Context, arg PutStatusValuesParams) error {
	_, err := q.db.ExecContext(ctx, putStatusValues,
		arg.EnrollmentID,
		arg.StatusID,
		pq.Array(arg.Paths),
		pq.Array(arg.ContainerTypes),
		pq.Array(arg.ValueTypes),
		pq.Array(arg.Vals),
	)
	return err
}

const removeAllEnrollmentSets = `-- name: RemoveAllEnrollmentSets :execresult
DELETE FROM
    enrollment_sets
WHERE
    enrollment_id = $1
`

func (q *Queries) RemoveAllEnrollmentSets(ctx context.Context, enrollmentID string) (sql.Result, error) {
	return q.db.ExecContext(ctx, removeAllEnrollmentSets, enrollmentID)
}

const removeDeclarationStatus = `-- name: RemoveDeclarationStatus :exec
DELETE FROM
    status_declarations
WHERE
    enrollment_id = $1
`

func (q *Queries) RemoveDeclarationStatus(ctx context.Context, enrollmentID string) error {
	_, err := q.db.ExecContext(ctx, removeDeclarationStatus, enrollmentID)
	return err
}

const removeEnrollmentSet = `-- name: RemoveEnrollmentSet :execresult
DELETE FROM enrollment_sets
WHERE
    enrollment_id = $1 AND
    set_name = $2
`

type RemoveEnrollmentSetParams struct {
	EnrollmentID string
	SetName      string
}

func (q *Queries) RemoveEnrollmentSet(ctx context.Context, arg RemoveEnrollmentSetParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, removeEnrollmentSet, arg.EnrollmentID, arg.SetName)
}

const removeSetDeclaration = `-- name: RemoveSetDeclaration :execresult
DELETE FROM set_declarations
WHERE
    set_name = $1 AND
    declaration_identifier = $2
`

type RemoveSetDeclarationParams struct {
	SetName               string
	DeclarationIdentifier string
}

func (q *Queries) RemoveSetDeclaration(ctx context.Context, arg RemoveSetDeclarationParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, removeSetDeclaration, arg.SetName, arg.DeclarationIdentifier)
}

const selectStatusErrors = `-- name: SelectStatusErrors :many
SELECT
    enrollment_id,
    path,
    error,
    status_id,
    created_at
FROM
    status_errors
WHERE
    enrollment_id = ANY($1::text[])
ORDER BY
    enrollment_id, id
LIMIT $3 OFFSET $2
`

type SelectStatusErrorsParams struct {
	Ids       []string
	RowOffset int32
	RowLimit  int32
}

type SelectStatusErrorsRow struct {
	EnrollmentID string
	Path         string
	Error        string
	StatusID     sql.NullString
	CreatedAt    time.Time
}

func (q *Queries) SelectStatusErrors(ctx context.Context, arg SelectStatusErrorsParams) ([]SelectStatusErrorsRow, error) {
	rows, err := q.db.QueryContext(ctx, selectStatusErrors, pq.Array(arg.Ids), arg.RowOffset, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelectStatusErrorsRow
	for rows.Next() {
		var i SelectStatusErrorsRow
		if err := rows.Scan(
			&i.EnrollmentID,
			&i.Path,
			&i.Error,
			&i.StatusID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectStatusReportByIndex = `-- name: SelectStatusReportByIndex :one
SELECT
    status_id,
    created_at,
    status_report
FROM
    status_reports
WHERE
    enrollment_id = $1
ORDER BY
    id DESC
LIMIT 1 OFFSET $2
`

type SelectStatusReportByIndexParams struct {
	EnrollmentID string
	RowOffset    int32
}

type SelectStatusReportByIndexRow struct {
	StatusID     sql.NullString
	CreatedAt    time.Time
	StatusReport string
}

// Index 0 is the most recent status report for the enrollment.
func (q *Queries) SelectStatusReportByIndex(ctx context.Context, arg SelectStatusReportByIndexParams) (SelectStatusReportByIndexRow, error) {
	row := q.db.QueryRowContext(ctx, selectStatusReportByIndex, arg.EnrollmentID, arg.RowOffset)
	var i SelectStatusReportByIndexRow
	err := row.Scan(&i.StatusID, &i.CreatedAt, &i.StatusReport)
	return i, err
}

const selectStatusReportByStatusID = `-- name: SelectStatusReportByStatusID :one
SELECT
    sr.status_id,
    sr.created_at,
    sr.status_report,
    (
        SELECT COUNT(*) FROM status_reports
        WHERE status_reports.enrollment_id = sr.enrollment_id
            AND status_reports.id > sr.id
    ) AS idx
FROM
    status_reports sr
WHERE
    sr.enrollment_id = $1
    AND sr.status_id = $2
ORDER BY
    sr.id DESC
LIMIT 1
`

type SelectStatusReportByStatusIDParams struct {
	EnrollmentID string
	StatusID     sql.NullString
}

type SelectStatusReportByStatusIDRow struct {
	StatusID     sql.NullString
	CreatedAt    time.Time
	StatusReport string
	Idx          int64
}

func (q *Queries) SelectStatusReportByStatusID(ctx context.Context, arg SelectStatusReportByStatusIDParams) (SelectStatusReportByStatusIDRow, error) {
	row := q.db.QueryRowContext(ctx, selectStatusReportByStatusID, arg.EnrollmentID, arg.StatusID)
	var i SelectStatusReportByStatusIDRow
	err := row.Scan(
		&i.StatusID,
		&i.CreatedAt,
		&i.StatusReport,
		&i.Idx,
	)
	return i, err
}

const storeDeclaration = `-- name: StoreDeclaration :execresult
INSERT INTO declarations
    (identifier, type, payload, server_token)
VALUES
    (
        $1::text,
        $2::text,
        $3::jsonb,
        encode(sha256(convert_to(concat($1::text, $2::text, $3::jsonb::text, CURRENT_TIMESTAMP::text, '0'), 'UTF8')), 'hex')
    )
ON CONFLICT (identifier) DO UPDATE
SET
    type         = excluded.type,
    payload      = excluded.payload,
    server_token = encode(sha256(convert_to(concat(excluded.identifier, excluded.type, excluded.payload::text, declarations.created_at::text, declarations.touched_ct::text), 'UTF8')), 'hex'),
    updated_at   = CURRENT_TIMESTAMP
WHERE
    declarations.type IS DISTINCT FROM excluded.type OR
    declarations.payload IS DISTINCT FROM excluded.payload
`

type StoreDeclarationParams struct {
	Identifier string
	Type       string
	Payload    string
}

// The WHERE on the conflict update leaves an unchanged declaration untouched,
// so it reports no affected rows and keeps its server token.
func (q *Queries) StoreDeclaration(ctx context.Context, arg StoreDeclarationParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, storeDeclaration, arg.Identifier, arg.Type, arg.Payload)
}

const storeEnrollmentSet = `-- name: StoreEnrollmentSet :execresult
INSERT INTO enrollment_sets
    (enrollment_id, set_name)
VALUES
    ($1, $2)
ON CONFLICT DO NOTHING
`

type StoreEnrollmentSetParams struct {
	EnrollmentID string
	SetName      string
}

func (q *Queries) StoreEnrollmentSet(ctx context.Context, arg StoreEnrollmentSetParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, storeEnrollmentSet, arg.EnrollmentID, arg.SetName)
}

const storeSetDeclaration = `-- name: StoreSetDeclaration :execresult
INSERT INTO set_declarations
    (declaration_identifier, set_name)
VALUES
    ($1, $2)
ON CONFLICT DO NOTHING
`

type StoreSetDeclarationParams struct {
	DeclarationIdentifier string
	SetName               string
}

func (q *Queries) StoreSetDeclaration(ctx context.Context, arg StoreSetDeclarationParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, storeSetDeclaration, arg.DeclarationIdentifier, arg.SetName)
}

const touchDeclaration = `-- name: TouchDeclaration :execresult
UPDATE
    declarations
SET
    touched_ct   = touched_ct + 1,
    server_token = encode(sha256(convert_to(concat(identifier, type, payload::text, created_at::text, (touched_ct + 1)::text), 'UTF8')), 'hex'),
    updated_at   = CURRENT_TIMESTAMP
WHERE
    identifier = $1
`

func (q *Queries) TouchDeclaration(ctx context.Context, identifier string) (sql.Result, error) {
	return q.db.ExecContext(ctx, touchDeclaration, identifier)
}
